name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to prepare"
        type: string
        required: true

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm i
      - run: npm run make-linux
      - name: Store release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-id
          path: out/make/linux/x64/steam-web-wrap-linux-x64-${{ inputs.version }}.zip
      - run: |
          echo "Current directory: $(pwd)"
          ls
          find out

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build-linux
    permissions:
      contents: write # Required for creating GitHub releases
    steps:
      - name: Create release
        id: create-release
        uses: actions/github-script@v7
        env:
          RELEASE_VERSION: ${{ inputs.version }}
        with:
          script: |
            const { RELEASE_VERSION } = process.env;
            const result = await github.request("POST /repos/{owner}/{repo}/releases", {
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: RELEASE_VERSION,
              name: RELEASE_VERSION,
              draft: true,
            });
            console.log(result);
