name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to prepare"
        type: string
        required: true

jobs:
  create-draft:
    name: Create Release Draft
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating GitHub releases
    steps:
      - name: Create release
        id: create-release
        uses: actions/github-script@v7
        env:
          RELEASE_VERSION: ${{ inputs.version }}
        with:
          script: |
            const { RELEASE_VERSION } = process.env;
            const {data: releaseData} = await github.request("POST /repos/{owner}/{repo}/releases", {
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: RELEASE_VERSION,
              name: RELEASE_VERSION,
              draft: true,
            });
            return releaseData.id;

      - name: Write release id
        run: echo ${{ steps.create-release.outputs.result }} > releaseId.txt

      - name: Store release id
        uses: actions/upload-artifact@v4
        with:
          name: release-id
          path: releaseId.txt
